export const ADD_PRODUCT_CALLER = "ADD_PRODUCT_CALLER"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR= "ADD_PRODUCT_ERROR"


export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS"
export const GET_ALL_PRODUCT_ERROR = "GET_ALL_PRODUCT_ERROR"
