export const ADD_CATEGORY_CALLER = 'ADD_CATEGORY_CALLER';
export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_END = 'ADD_CATEGORY_END';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const GET_ALL_CATEGORY_CALLER = 'ADD_CATEGORY_CALLER';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';
