export const ADD_CATEGORY_CALLER = 'ADD_CATEGORY_CALLER';
export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_END = 'ADD_CATEGORY_END';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const GET_ALL_CATEGORY_CALLER = 'GET_ALL_CATEGORY_CALLER';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';


export const EDIT_CATEGORY_CALLER = 'EDIT_CATEGORY_CALLER';
export const EDIT_CATEGORY_START = 'EDIT_CATEGORY_START';
export const EDIT_CATEGORY_END = 'EDIT_CATEGORY_END';
export const EDIt_CATEGORY_SUCCESS = 'EDIt_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';

export const CATEGORY_REMOVE_MODEL_OPEN = 'CATEGORY_REMOVE_MODEL_OPEN';
export const CATEGORY_REMOVE_MODEL_CLOSE = 'CATEGORY_REMOVE_MODEL_CLOSE';
export const IS_ANSWERED_SUCCESS = 'IS_ANSWERED_SUCCESS';
export const IS_ANSWERED_FAILED = 'IS_ANSWERED_FAILED';


export const CATEGORY_DELETE_START = 'CATEGORY_DELETE_START';
export const CATEGORY_DELETE_END = 'CATEGORY_DELETE_END';
export const CATEGORY_DELETE_CALLER = 'CATEGORY_DELETE_CALLER';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAILED = 'CATEGORY_DELETE_FAILED';
